### PR TITLE
Implement GitHub Actions

### LINKED ISSUE #239: Move from Travis CI to GitHub Actions?
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
~~You might also want to reference the "build" status in `README.md`.~~

I think you need to "activate" GitHub Actions on `master` after which I can rebase this for testing.

Closes #239.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
> You might also want to reference the "build" status in README.md.

Don't merge yet. Let me take care of this change.

**Comment by elbrujohalcon** [comment]
I removed travis already. Let me know when to merge, @ferigis / @paulo-ferraz-oliveira.

**Comment by paulo-ferraz-oliveira** [comment]
I'm Okay with merging, since I have no further actions on this, at the moment.

**Comment by elbrujohalcon** [comment]
…aaaaand merged!

**Pull request merged**
