### PR TITLE
Updated gun to 2.0.0

### PR DESCRIPTION
**Pull request by HernanRivasAcosta**
Based on the work by @jainygaurav on #246 but updated to wok on the newly released 2.0.0 version of cowboy.

### CODE REVIEW

**Comment by Neustradamus** [comment]
To follow

**Comment by elbrujohalcon** [comment]
I allowed CI to run… but now it fails because Gun doesn't work with old erlangs.

**Comment by HernanRivasAcosta** [comment]
Because of the [fixes to crypto made in Erlang 25.1](https://www.erlang.org/news/158) I can not make this work on ananything earlier that that version.

@ferigis that might mean we should bump this to a new major version since it loses compatibility with the all but the latest Erlang versions.

**Comment by HernanRivasAcosta** [comment]
@ferigis I'm tempted to merge this PR and increase the version. I've been using this branch for a while now and I can confirm it works perfectly fine, even if the tests are not passing.

What do you think?

**Comment by ferigis** [comment]
hi @HernanRivasAcosta, sorry for the late response. 

Yes, lets bump to a major version.

Thanks

**Comment by essen** [comment]
Please use Gun 2.0.1 so you get a Cowlib version that's compatible with OTP-26 otherwise you'll get a compilation error.

**Comment by dsrosario** [comment]
Hello @elbrujohalcon, any plan to approve and merge this PR?

**Comment by elbrujohalcon** [comment]
@dsrosario: Not on my side. You should ask @ferigis or @HernanRivasAcosta :)

**Comment by dsrosario** [comment]
But is there any intension to update the CI to check with latest OTP version (like 26, 25 and 24) instead of the old one's? Maybe some guidance here regarding what Erlang versions to support may help.

**Comment by elbrujohalcon** [comment]
Yeah, usually what we do is to support latest 3 versions. In this case 24, 25 and 26. But, again, I defer to @ferigis and @HernanRivasAcosta for decisions like that on this repo. They're the maintainers and the repo admins.

**Comment by dsrosario** [comment]
@ferigis @HernanRivasAcosta any news?

**Comment by dsrosario** [comment]
This PR is obsolete. #258 bumped gun to 2.1.0

**Pull request closed without merging**
