### PR TITLE
These changes were done to make apns4erl (v2) work with gun-2.0.0-rc.1.

### PR DESCRIPTION
**Pull request by jainygaurav**
For details, please refer to:

https://github.com/inaka/apns4erl/issues/242
https://github.com/inaka/apns4erl/issues/245
https://github.com/ninenines/gun/issues/261
https://github.com/ninenines/gun/issues/263

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Cool, thanks. No further changes should be required, at a first glance. Let's just wait `2.0.0` is released so we don't depend on an interface that might break, OK?

**Comment by jainygaurav** [comment]
OK. Only one thing I created this `pull request` for `master` branch, though I was not sure whether I should have created it for a specific `inaka/apns4erl `- gun-2.0.0 branch, if there is any.

**Comment by paulo-ferraz-oliveira** [comment]
You should usually create a pull request from a branch stemming from `master`.

So, that way, your `master` branch should be sync'ed with `apns4erl`'s and then your pull request start from a local branch to `master`.

I guess the main reason for this (which might not apply in your case) is that you can continue depending on a stable `master` branch while discussion/updates take place in a separate branch. Check e.g. https://guides.github.com/introduction/flow/.

**Comment by ferigis** [comment]
hi @jainygaurav !

Thanks a lot for your contribution. As Paulo wrote, we will keep this PR opened until the gun 2.0 is available, so then we will use this PR for sure.

Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
Here's a request for `gun` 2.0.0 to be released 😄: https://github.com/ninenines/gun/issues/268. You can watch that so you can later update this, @jainygaurav.

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by paulo-ferraz-oliveira** [comment]
> Any news about it?

None. This depends on `gun` 2.0.0. As long as that's not out, this is not out. 😄

**Comment by HernanRivasAcosta** [comment]
Gun's version 2.0.0 just released.

I know this is a very old PR @jainygaurav, but we need to change the version of gun in this PR (from ``2.0.0-rc.1`` to ``2.0.0``).

Let me know if you want/can do that, I will test it and merge it. Otherwise I'm happy to make a new PR from your branch so we can keep your commit.

**Comment by paulo-ferraz-oliveira** [comment]
Yup, great stuff. After that, we can do #241. 😄

**Comment by HernanRivasAcosta** [comment]
Superseded by #256

**Pull request closed without merging**
