### PR TITLE
Add mutable-content key to aps dictionary.

### PR DESCRIPTION
**Pull request by richardtylee**
We would like to add the mutable-content key to aps dictionary.  The mutable-content field tells iOS that the notification has content that can be changed by a service extension before delivery.  It allows for functionality like rich notifications.

Documentation:
https://developer.apple.com/reference/usernotifications/unnotificationserviceextension
http://willowtreeapps.com/blog/wwdc-2016-rich-notifications-in-ios-10/

### CODE REVIEW

**Comment by jwheare** [comment]
I believe `apns_extra` was added to allow for such new fields without having to change the record definition and upgrade the dependency each time. Is there a reason you need to define it separately?

**Comment by richardleebr** [comment]
Ah, I was not aware of that field.  Thanks @jwheare .  I'll give it a try and close this PR out when I've verified it.

**Comment by richardleebr** [comment]
I'm using this in an Elixir project, but the following doesn't seem to work:

`apns_msg(
  apns_extra:  [{:"mutable-content", 1}]
)`

Is it the way the atom is converted to binary?

**Comment by jwheare** [comment]
@richardleebr in our Erlang project we're sending:

`#apns_msg{ apns_extra=[ {'mutable-content', 1} ] }`

It isn't erroring out either, but we haven't build the iOS app side out so I can't confirm whether it's actually working yet :) I'll let you know when we get there.

One thing you might want to check is your `UNNotificationExtensionCategory`. I believe a corresponding `category` should be set in the `apns_extra` field for rich notifications to work.

**Pull request closed without merging**
